name: Kura SBOM upload

on:
  schedule:
    # At 04:52 on Saturday
    - cron: "52 4 * * 6"
  workflow_dispatch:
    inputs:
      target_branch:
        type: string
        default: 'develop'
        required: true
  workflow_run:
    workflows: ["Release Notes automation"]
    types:
      - completed

permissions:
  contents: read
  packages: read

jobs:
  call-workflow-in-public-repo:
    uses: eclipse-kura/.github/.github/workflows/_shared-sbom-cyclonedx.yml@main
    with:
      # The parent project UUID the uploaded SBOM should be associated with.
      # Refer to https://sbom.eclipse.org/ to retrieve the UUID.
      dependency-track-id: '5b28eee9-de0f-4cf5-bb5d-35d15f3a3dfa'
